apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: 2019-03-19T14:38:30Z
    generation: 3
    labels:
      app: logtofile
    name: logtofile
    namespace: jei-logging
    resourceVersion: "296900"
    selfLink: /apis/apps.openshift.io/v1/namespaces/jei-logging/deploymentconfigs/logtofile
    uid: aa7b95f4-4a54-11e9-bdbd-0611106f25de
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: logtofile
      deploymentconfig: logtofile
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: logtofile
          deploymentconfig: logtofile
      spec:
        containers:
        - args:
          - /bin/sh
          - -c
          - sleep 5 && tail -n+1 -f /tmp/datelog.txt
          image: docker.io/busybox:latest
          imagePullPolicy: Always
          name: logging-sidecar
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /tmp
            name: tmp
        - image: docker.io/wkulhanek/logtofile@sha256:ef013bc12e3d6baa56ff1b8b9323bdecfec69d2898ce7b4a276089e55fdebe0c
          imagePullPolicy: Always
          name: logtofile
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /tmp
            name: tmp
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: tmp
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - logtofile
        from:
          kind: ImageStreamTag
          name: logtofile:latest
          namespace: jei-logging
        lastTriggeredImage: docker.io/wkulhanek/logtofile@sha256:ef013bc12e3d6baa56ff1b8b9323bdecfec69d2898ce7b4a276089e55fdebe0c
      type: ImageChange
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2019-03-19T15:12:05Z
      lastUpdateTime: 2019-03-19T15:12:08Z
      message: replication controller "logtofile-2" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: 2019-03-19T21:32:29Z
      lastUpdateTime: 2019-03-19T21:32:29Z
      message: Deployment config has minimum availability.
      status: "True"
      type: Available
    details:
      causes:
      - imageTrigger:
          from:
            kind: DockerImage
            name: docker.io/busybox:latest
        type: ImageChange
      message: image change
    latestVersion: 2
    observedGeneration: 3
    readyReplicas: 1
    replicas: 1
    unavailableReplicas: 0
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
