apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: 2019-03-21T17:53:48Z
    labels:
      build: tasks
    name: tasks
    namespace: jei-tasks-dev
    resourceVersion: "1039179"
    selfLink: /apis/build.openshift.io/v1/namespaces/jei-tasks-dev/buildconfigs/tasks
    uid: 474a7c4a-4c02-11e9-b999-0611106f25de
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: tasks:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: jboss-eap71-openshift:1.3
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: 8q3b5s4B0GcSkvHiS4eG
      type: GitHub
    - generic:
        secret: 3oHZC0p2v5bDbZcPt1MK
      type: Generic
  status:
    lastVersion: 15
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
