apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: 2019-03-21T17:56:14Z
    generation: 33
    labels:
      app: tasks
    name: tasks
    namespace: jei-tasks-dev
    resourceVersion: "1039608"
    selfLink: /apis/apps.openshift.io/v1/namespaces/jei-tasks-dev/deploymentconfigs/tasks
    uid: 9e975260-4c02-11e9-b999-0611106f25de
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: tasks
      deploymentconfig: tasks
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: tasks
          deploymentconfig: tasks
      spec:
        containers:
        - image: docker-registry.default.svc:5000/jei-tasks-dev/tasks:1.1-3
          imagePullPolicy: IfNotPresent
          name: tasks
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/eap/standalone/configuration/application-users.properties
            name: jboss-config
            subPath: application-users.properties
          - mountPath: /opt/eap/standalone/configuration/application-roles.properties
            name: jboss-config1
            subPath: application-roles.properties
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: tasks-config
          name: jboss-config
        - configMap:
            defaultMode: 420
            name: tasks-config
          name: jboss-config1
    test: false
    triggers: []
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2019-03-21T20:28:06Z
      lastUpdateTime: 2019-03-21T20:28:06Z
      message: Deployment config has minimum availability.
      status: "True"
      type: Available
    - lastTransitionTime: 2019-03-22T15:22:25Z
      lastUpdateTime: 2019-03-22T15:22:27Z
      message: replication controller "tasks-14" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: "True"
      type: Progressing
    details:
      causes:
      - type: Manual
      message: manual change
    latestVersion: 14
    observedGeneration: 33
    readyReplicas: 1
    replicas: 1
    unavailableReplicas: 0
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
